# Generated by Django 4.2.4 on 2023-08-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='attributes',
            new_name='attribute',
        ),
        migrations.RenameField(
            model_name='productvariation',
            old_name='colors',
            new_name='color',
        ),
    ]
