# Generated by Django 4.2.4 on 2023-08-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='description',
            field=models.TextField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videoprovider',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
