# Generated by Django 4.2.4 on 2023-08-30 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_attributes_productvariation_attribute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=15)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attribute')),
            ],
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
