# Generated by Django 4.2.4 on 2023-08-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_attributevalue_remove_productvariation_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='attribute',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='attribute',
            field=models.ManyToManyField(related_name='attributes', to='product.attribute', verbose_name='Avaiable attributes'),
        ),
    ]
