# Generated by Django 4.2.4 on 2023-08-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_attribute_created_at_brand_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
