# Generated by Django 4.2.4 on 2023-08-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_product_name_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVideo',
        ),
    ]
