# Generated by Django 4.2.4 on 2023-08-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_attribute_productvariation_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='attribute_values',
            field=models.ManyToManyField(to='product.attributevalue'),
        ),
    ]
