# Generated by Django 4.2.4 on 2023-08-29 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='product_variation',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='colors',
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='product.product'),
        ),
        migrations.CreateModel(
            name='ProductVariationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attribute')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariation')),
            ],
        ),
        migrations.AddField(
            model_name='productprice',
            name='product_variation_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.productvariationoption'),
            preserve_default=False,
        ),
    ]
