# Generated by Django 4.2.4 on 2023-08-30 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='attribute_values',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='attribute_values',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='product.attributevalue'),
        ),
    ]
