# Generated by Django 4.2.4 on 2023-08-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_productvariation_attribute_values_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='attribute_values',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='attribute_values',
            field=models.ManyToManyField(related_name='attribute_values', to='product.attributevalue'),
        ),
    ]
