# Generated by Django 4.2.4 on 2023-08-30 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_productvariation_attribute_values_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='attribute_values',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='attributes',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='product.attribute'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='attribute_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='product.attributevalue'),
        ),
    ]
