# Generated by Django 4.2.4 on 2023-08-30 22:12

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productvariation_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='attribute_value',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='attribute', chained_model_field='attribute', on_delete=django.db.models.deletion.CASCADE, to='product.attributevalue'),
        ),
    ]
